# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Share' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Share
# U-Share SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’

    # 集成新浪微博
    pod ‘UMengUShare/Social/Sina'
    pod ‘Masonry’
end
